// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity playerSync;
        }

        public static unsafe _3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 38");
            }

            var orig = new _3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519();
            var comp = (Interop*)data;
            orig.playerSync = comp->playerSync;
            return orig;
        }

        public Entity playerSync;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 38;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(playerSync, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.playerSync = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(playerSync, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.playerSync = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.playerSync,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.playerSync == entity) {
                this.playerSync = Entity.InvalidRelative;
            }
        }
        
        public _3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519(
        Entity entity,
        Entity playerSync
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.playerSync = playerSync; 
        }
        
        public static void Serialize(_3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.playerSync);
        }
        
        public static _3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataplayerSync = bitStream.ReadEntity();
    
            return new _3941f9337bf07904f8ebd80981d7e64f_b202adf0df3740e384107a17bd00b519()
            {
                Entity = entity,
                Routing = target,
                playerSync = dataplayerSync
            };   
        }
    }

}
