// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity askerSync;
        }

        public static unsafe _3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 45");
            }

            var orig = new _3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8();
            var comp = (Interop*)data;
            orig.askerSync = comp->askerSync;
            return orig;
        }

        public Entity askerSync;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 45;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(askerSync, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.askerSync = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(askerSync, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.askerSync = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.askerSync,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.askerSync == entity) {
                this.askerSync = Entity.InvalidRelative;
            }
        }
        
        public _3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8(
        Entity entity,
        Entity askerSync
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.askerSync = askerSync; 
        }
        
        public static void Serialize(_3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.askerSync);
        }
        
        public static _3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataaskerSync = bitStream.ReadEntity();
    
            return new _3941f9337bf07904f8ebd80981d7e64f_699d584833914ddf87fc959a13b2def8()
            {
                Entity = entity,
                Routing = target,
                askerSync = dataaskerSync
            };   
        }
    }

}
