// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 damage;
        }

        public static unsafe _5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 37");
            }

            var orig = new _5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562();
            var comp = (Interop*)data;
            orig.damage = comp->damage;
            return orig;
        }

        public System.Int32 damage;
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 37;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562(
        Entity entity,
        System.Int32 damage
)
        {
            Entity = entity;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.damage = damage; 
        }
        
        public static void Serialize(_5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteIntegerRange(commandData.damage, 32, -2147483648);
        }
        
        public static _5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datadamage = bitStream.ReadIntegerRange(32, -2147483648);
    
            return new _5358ed04715b0f148a60e93c83f08be0_215915084e114f92bc20eb4f102e7562()
            {
                Entity = entity,
                Routing = target,
                damage = datadamage
            };   
        }
    }

}