// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Byte Enabled;
        }

        public static unsafe _5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 1) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 1) " +
                    "for command with ID 19");
            }

            var orig = new _5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc();
            var comp = (Interop*)data;
            orig.Enabled = comp->Enabled != 0;
            return orig;
        }

        public System.Boolean Enabled;
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 19;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public _5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc(
        Entity entity,
        System.Boolean Enabled
)
        {
            Entity = entity;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.Enabled = Enabled; 
        }
        
        public static void Serialize(_5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteBool(commandData.Enabled);
        }
        
        public static _5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataEnabled = bitStream.ReadBool();
    
            return new _5358ed04715b0f148a60e93c83f08be0_eea03180c9524795ae2b5bb889afe6fc()
            {
                Entity = entity,
                Routing = target,
                Enabled = dataEnabled
            };   
        }
    }

}