// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;

    public struct _5358ed04715b0f148a60e93c83f08be0_2358625368182078286 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 m_IntPlayerState;
            [FieldOffset(4)]
            public System.Int32 m_Global_Health;
            [FieldOffset(8)]
            public System.Int32 m_Player_Health;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_IntPlayerStateMask;
            m_IntPlayerStateSimulationFrame = frame;
            FieldsMask |= _5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_Global_HealthMask;
            m_Global_HealthSimulationFrame = frame;
            FieldsMask |= _5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_Player_HealthMask;
            m_Player_HealthSimulationFrame = frame;
        }

        public static unsafe _5358ed04715b0f148a60e93c83f08be0_2358625368182078286 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 12) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 12) " +
                    "for component with ID 165");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 165");
            }

            var orig = new _5358ed04715b0f148a60e93c83f08be0_2358625368182078286();

            var comp = (Interop*)data;

            orig.m_IntPlayerState = comp->m_IntPlayerState;
            orig.m_Global_Health = comp->m_Global_Health;
            orig.m_Player_Health = comp->m_Player_Health;

            return orig;
        }


        public static uint m_IntPlayerStateMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame m_IntPlayerStateSimulationFrame;
        public System.Int32 m_IntPlayerState;
        public static uint m_Global_HealthMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame m_Global_HealthSimulationFrame;
        public System.Int32 m_Global_Health;
        public static uint m_Player_HealthMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame m_Player_HealthSimulationFrame;
        public System.Int32 m_Player_Health;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 165;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.Int32 _m_IntPlayerState_Min = -2147483648;
        private static readonly System.Int32 _m_IntPlayerState_Max = 2147483647;
        private static readonly System.Int32 _m_Global_Health_Min = -2147483648;
        private static readonly System.Int32 _m_Global_Health_Max = 2147483647;
        private static readonly System.Int32 _m_Player_Health_Min = -2147483648;
        private static readonly System.Int32 _m_Player_Health_Max = 2147483647;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_5358ed04715b0f148a60e93c83f08be0_2358625368182078286)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.m_IntPlayerStateSimulationFrame = other.m_IntPlayerStateSimulationFrame;
                this.m_IntPlayerState = other.m_IntPlayerState;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.m_Global_HealthSimulationFrame = other.m_Global_HealthSimulationFrame;
                this.m_Global_Health = other.m_Global_Health;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.m_Player_HealthSimulationFrame = other.m_Player_HealthSimulationFrame;
                this.m_Player_Health = other.m_Player_Health;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_5358ed04715b0f148a60e93c83f08be0_2358625368182078286 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.m_IntPlayerState, _m_IntPlayerState_Min, _m_IntPlayerState_Max, "_5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_IntPlayerState", logger);

                data.m_IntPlayerState = Coherence.Utils.Bounds.Clamp(data.m_IntPlayerState, _m_IntPlayerState_Min, _m_IntPlayerState_Max);

                var fieldValue = data.m_IntPlayerState;



                bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.m_Global_Health, _m_Global_Health_Min, _m_Global_Health_Max, "_5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_Global_Health", logger);

                data.m_Global_Health = Coherence.Utils.Bounds.Clamp(data.m_Global_Health, _m_Global_Health_Min, _m_Global_Health_Max);

                var fieldValue = data.m_Global_Health;



                bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.m_Player_Health, _m_Player_Health_Min, _m_Player_Health_Max, "_5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_Player_Health", logger);

                data.m_Player_Health = Coherence.Utils.Bounds.Clamp(data.m_Player_Health, _m_Player_Health_Min, _m_Player_Health_Max);

                var fieldValue = data.m_Player_Health;



                bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
            }

            mask >>= 1;

            return mask;
        }

        public static _5358ed04715b0f148a60e93c83f08be0_2358625368182078286 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new _5358ed04715b0f148a60e93c83f08be0_2358625368182078286();
            if (bitStream.ReadMask())
            {

                val.m_IntPlayerState = bitStream.ReadIntegerRange(32, -2147483648);
                val.FieldsMask |= _5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_IntPlayerStateMask;
            }
            if (bitStream.ReadMask())
            {

                val.m_Global_Health = bitStream.ReadIntegerRange(32, -2147483648);
                val.FieldsMask |= _5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_Global_HealthMask;
            }
            if (bitStream.ReadMask())
            {

                val.m_Player_Health = bitStream.ReadIntegerRange(32, -2147483648);
                val.FieldsMask |= _5358ed04715b0f148a60e93c83f08be0_2358625368182078286.m_Player_HealthMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_5358ed04715b0f148a60e93c83f08be0_2358625368182078286(" +
                $" m_IntPlayerState: { this.m_IntPlayerState }" +
                $" m_Global_Health: { this.m_Global_Health }" +
                $" m_Player_Health: { this.m_Player_Health }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }


}