// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;

    public struct _61db515efe9556c45853cdc384e6813b_6363404363339079209 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 GameID;
            [FieldOffset(4)]
            public System.Byte CanAttack;
            [FieldOffset(5)]
            public System.Byte IsStunned;
            [FieldOffset(6)]
            public System.Int32 IntMovementType;
            [FieldOffset(10)]
            public System.Int32 IntNPCBehavior;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.GameIDMask;
            GameIDSimulationFrame = frame;
            FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.CanAttackMask;
            CanAttackSimulationFrame = frame;
            FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.IsStunnedMask;
            IsStunnedSimulationFrame = frame;
            FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.IntMovementTypeMask;
            IntMovementTypeSimulationFrame = frame;
            FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.IntNPCBehaviorMask;
            IntNPCBehaviorSimulationFrame = frame;
        }

        public static unsafe _61db515efe9556c45853cdc384e6813b_6363404363339079209 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 14) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 14) " +
                    "for component with ID 203");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 203");
            }

            var orig = new _61db515efe9556c45853cdc384e6813b_6363404363339079209();

            var comp = (Interop*)data;

            orig.GameID = comp->GameID;
            orig.CanAttack = comp->CanAttack != 0;
            orig.IsStunned = comp->IsStunned != 0;
            orig.IntMovementType = comp->IntMovementType;
            orig.IntNPCBehavior = comp->IntNPCBehavior;

            return orig;
        }


        public static uint GameIDMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame GameIDSimulationFrame;
        public System.Int32 GameID;
        public static uint CanAttackMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame CanAttackSimulationFrame;
        public System.Boolean CanAttack;
        public static uint IsStunnedMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame IsStunnedSimulationFrame;
        public System.Boolean IsStunned;
        public static uint IntMovementTypeMask => 0b00000000000000000000000000001000;
        public AbsoluteSimulationFrame IntMovementTypeSimulationFrame;
        public System.Int32 IntMovementType;
        public static uint IntNPCBehaviorMask => 0b00000000000000000000000000010000;
        public AbsoluteSimulationFrame IntNPCBehaviorSimulationFrame;
        public System.Int32 IntNPCBehavior;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 203;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000011111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 5;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.Int32 _GameID_Min = -99;
        private static readonly System.Int32 _GameID_Max = 99;
        private static readonly System.Int32 _IntMovementType_Min = -99;
        private static readonly System.Int32 _IntMovementType_Max = 99;
        private static readonly System.Int32 _IntNPCBehavior_Min = -99;
        private static readonly System.Int32 _IntNPCBehavior_Max = 99;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_61db515efe9556c45853cdc384e6813b_6363404363339079209)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.GameIDSimulationFrame = other.GameIDSimulationFrame;
                this.GameID = other.GameID;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.CanAttackSimulationFrame = other.CanAttackSimulationFrame;
                this.CanAttack = other.CanAttack;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.IsStunnedSimulationFrame = other.IsStunnedSimulationFrame;
                this.IsStunned = other.IsStunned;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.IntMovementTypeSimulationFrame = other.IntMovementTypeSimulationFrame;
                this.IntMovementType = other.IntMovementType;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.IntNPCBehaviorSimulationFrame = other.IntNPCBehaviorSimulationFrame;
                this.IntNPCBehavior = other.IntNPCBehavior;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_61db515efe9556c45853cdc384e6813b_6363404363339079209 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 5);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.GameID, _GameID_Min, _GameID_Max, "_61db515efe9556c45853cdc384e6813b_6363404363339079209.GameID", logger);

                data.GameID = Coherence.Utils.Bounds.Clamp(data.GameID, _GameID_Min, _GameID_Max);

                var fieldValue = data.GameID;



                bitStream.WriteIntegerRange(fieldValue, 8, -99);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.CanAttack;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.IsStunned;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.IntMovementType, _IntMovementType_Min, _IntMovementType_Max, "_61db515efe9556c45853cdc384e6813b_6363404363339079209.IntMovementType", logger);

                data.IntMovementType = Coherence.Utils.Bounds.Clamp(data.IntMovementType, _IntMovementType_Min, _IntMovementType_Max);

                var fieldValue = data.IntMovementType;



                bitStream.WriteIntegerRange(fieldValue, 8, -99);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.IntNPCBehavior, _IntNPCBehavior_Min, _IntNPCBehavior_Max, "_61db515efe9556c45853cdc384e6813b_6363404363339079209.IntNPCBehavior", logger);

                data.IntNPCBehavior = Coherence.Utils.Bounds.Clamp(data.IntNPCBehavior, _IntNPCBehavior_Min, _IntNPCBehavior_Max);

                var fieldValue = data.IntNPCBehavior;



                bitStream.WriteIntegerRange(fieldValue, 8, -99);
            }

            mask >>= 1;

            return mask;
        }

        public static _61db515efe9556c45853cdc384e6813b_6363404363339079209 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(5);
            }

            var val = new _61db515efe9556c45853cdc384e6813b_6363404363339079209();
            if (bitStream.ReadMask())
            {

                val.GameID = bitStream.ReadIntegerRange(8, -99);
                val.FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.GameIDMask;
            }
            if (bitStream.ReadMask())
            {

                val.CanAttack = bitStream.ReadBool();
                val.FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.CanAttackMask;
            }
            if (bitStream.ReadMask())
            {

                val.IsStunned = bitStream.ReadBool();
                val.FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.IsStunnedMask;
            }
            if (bitStream.ReadMask())
            {

                val.IntMovementType = bitStream.ReadIntegerRange(8, -99);
                val.FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.IntMovementTypeMask;
            }
            if (bitStream.ReadMask())
            {

                val.IntNPCBehavior = bitStream.ReadIntegerRange(8, -99);
                val.FieldsMask |= _61db515efe9556c45853cdc384e6813b_6363404363339079209.IntNPCBehaviorMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_61db515efe9556c45853cdc384e6813b_6363404363339079209(" +
                $" GameID: { this.GameID }" +
                $" CanAttack: { this.CanAttack }" +
                $" IsStunned: { this.IsStunned }" +
                $" IntMovementType: { this.IntMovementType }" +
                $" IntNPCBehavior: { this.IntNPCBehavior }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(5, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(5, '0') })";
        }
    }

}
