// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray GameEffectID;
            [FieldOffset(16)]
            public Entity damagerSync;
        }

        public static unsafe _61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 20) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 20) " +
                    "for command with ID 86");
            }

            var orig = new _61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a();
            var comp = (Interop*)data;
            orig.GameEffectID = comp->GameEffectID.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->GameEffectID.Data, (int)comp->GameEffectID.Length) : null;
            orig.damagerSync = comp->damagerSync;
            return orig;
        }

        public System.String GameEffectID;
        public Entity damagerSync;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 86;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(damagerSync, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.damagerSync = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(damagerSync, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.damagerSync = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.damagerSync,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.damagerSync == entity) {
                this.damagerSync = Entity.InvalidRelative;
            }
        }
        
        public _61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a(
        Entity entity,
        System.String GameEffectID,
        Entity damagerSync
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.GameEffectID = GameEffectID; 
            this.damagerSync = damagerSync; 
        }
        
        public static void Serialize(_61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(commandData.GameEffectID);
            bitStream.WriteEntity(commandData.damagerSync);
        }
        
        public static _61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataGameEffectID = bitStream.ReadShortString();
            var datadamagerSync = bitStream.ReadEntity();
    
            return new _61db515efe9556c45853cdc384e6813b_d97a67914faf4da7953aba4ef959103a()
            {
                Entity = entity,
                Routing = target,
                GameEffectID = dataGameEffectID,
                damagerSync = datadamagerSync
            };   
        }
    }

}
