// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity AskerSync;
        }

        public static unsafe _c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for command with ID 88");
            }

            var orig = new _c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e();
            var comp = (Interop*)data;
            orig.AskerSync = comp->AskerSync;
            return orig;
        }

        public Entity AskerSync;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 88;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(AskerSync, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.AskerSync = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(AskerSync, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.AskerSync = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.AskerSync,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.AskerSync == entity) {
                this.AskerSync = Entity.InvalidRelative;
            }
        }
        
        public _c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e(
        Entity entity,
        Entity AskerSync
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.AskerSync = AskerSync; 
        }
        
        public static void Serialize(_c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.AskerSync);
        }
        
        public static _c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataAskerSync = bitStream.ReadEntity();
    
            return new _c473af9c10567024caf206bf6752a656_1dd3fd6dfca04fb084372d425002546e()
            {
                Entity = entity,
                Routing = target,
                AskerSync = dataAskerSync
            };   
        }
    }

}
