// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 damage;
            [FieldOffset(4)]
            public System.Int32 damageType;
            [FieldOffset(8)]
            public Entity Damagersync;
        }

        public static unsafe _c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 12) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 12) " +
                    "for command with ID 124");
            }

            var orig = new _c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7();
            var comp = (Interop*)data;
            orig.damage = comp->damage;
            orig.damageType = comp->damageType;
            orig.Damagersync = comp->Damagersync;
            return orig;
        }

        public System.Int32 damage;
        public System.Int32 damageType;
        public Entity Damagersync;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 124;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(Damagersync, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.Damagersync = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(Damagersync, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.Damagersync = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.Damagersync,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.Damagersync == entity) {
                this.Damagersync = Entity.InvalidRelative;
            }
        }
        
        public _c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7(
        Entity entity,
        System.Int32 damage,
        System.Int32 damageType,
        Entity Damagersync
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.damage = damage; 
            this.damageType = damageType; 
            this.Damagersync = Damagersync; 
        }
        
        public static void Serialize(_c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7 commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteIntegerRange(commandData.damage, 32, -2147483648);
            bitStream.WriteIntegerRange(commandData.damageType, 32, -2147483648);
            bitStream.WriteEntity(commandData.Damagersync);
        }
        
        public static _c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var datadamage = bitStream.ReadIntegerRange(32, -2147483648);
            var datadamageType = bitStream.ReadIntegerRange(32, -2147483648);
            var dataDamagersync = bitStream.ReadEntity();
    
            return new _c473af9c10567024caf206bf6752a656_8b1c81e7d6a44294af969d3c94e1e2f7()
            {
                Entity = entity,
                Routing = target,
                damage = datadamage,
                damageType = datadamageType,
                Damagersync = dataDamagersync
            };   
        }
    }

}
