// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_c473af9c10567024caf206bf6752a656_76d88dca78064cbea5233f4734ab5bd3 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_c473af9c10567024caf206bf6752a656_98c1411584cc4bf1aba7e1771fdde594 : IntAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_c473af9c10567024caf206bf6752a656_5919305605642209624);
        public override string CoherenceComponentName => "_c473af9c10567024caf206bf6752a656_5919305605642209624";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.GetInteger(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetInteger(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_c473af9c10567024caf206bf6752a656_5919305605642209624)coherenceComponent).DummyParry;

            var simFrame = ((_c473af9c10567024caf206bf6752a656_5919305605642209624)coherenceComponent).DummyParrySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_c473af9c10567024caf206bf6752a656_5919305605642209624)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.DummyParry = Value;
            }
            else
            {
                update.DummyParry = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.DummyParrySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _c473af9c10567024caf206bf6752a656_5919305605642209624();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_c473af9c10567024caf206bf6752a656 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_c473af9c10567024caf206bf6752a656>();
        
        private global::Dummy _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5_CommandTarget;
        private global::Dummy _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f_CommandTarget;
        private global::Dummy _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["76d88dca78064cbea5233f4734ab5bd3"] = new Binding_c473af9c10567024caf206bf6752a656_76d88dca78064cbea5233f4734ab5bd3(),
            ["98c1411584cc4bf1aba7e1771fdde594"] = new Binding_c473af9c10567024caf206bf6752a656_98c1411584cc4bf1aba7e1771fdde594(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_c473af9c10567024caf206bf6752a656()
        {
            bakedCommandBindings.Add("e33d948cb4b64ce2816cba73ee1638b5", BakeCommandBinding__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5);
            bakedCommandBindings.Add("df4c30db719f4e8494aee9fa09f11b9f", BakeCommandBinding__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f);
            bakedCommandBindings.Add("1c65cbe28daf476c87b1ab1f32198cf6", BakeCommandBinding__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5_CommandTarget = (global::Dummy)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Dummy.TakeMeleeSync", "(System.Int32Coherence.Toolkit.CoherenceSyncSystem.Int32)", SendCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5, ReceiveLocalCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5, MessageTarget.All, _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5_CommandTarget, false);
        }
        
        private void SendCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5(MessageTarget target, object[] args)
        {
            var command = new _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5();
            
            int i = 0;
            command.DirectionNESO = (System.Int32)args[i++];
            command.sync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
            command.damage = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5(MessageTarget target, object[] args)
        {
            var command = new _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5();
            
            int i = 0;
            command.DirectionNESO = (System.Int32)args[i++];
            command.sync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
            command.damage = (System.Int32)args[i++];
            
            ReceiveCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5(command);
        }

        private void ReceiveCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5(_c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5 command)
        {
            var target = _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5_CommandTarget;
            
            target.TakeMeleeSync((System.Int32)(command.DirectionNESO),bridge.EntityIdToCoherenceSync(command.sync),(System.Int32)(command.damage));
        }
    
        private void BakeCommandBinding__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f_CommandTarget = (global::Dummy)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Dummy.TakeDamageSync", "(System.Int32Coherence.Toolkit.CoherenceSync)", SendCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f, ReceiveLocalCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f, MessageTarget.All, _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f_CommandTarget, false);
        }
        
        private void SendCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f(MessageTarget target, object[] args)
        {
            var command = new _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f();
            
            int i = 0;
            command.damage = (System.Int32)args[i++];
            command.Damagersync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f(MessageTarget target, object[] args)
        {
            var command = new _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f();
            
            int i = 0;
            command.damage = (System.Int32)args[i++];
            command.Damagersync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
            
            ReceiveCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f(command);
        }

        private void ReceiveCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f(_c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f command)
        {
            var target = _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f_CommandTarget;
            
            target.TakeDamageSync((System.Int32)(command.damage),bridge.EntityIdToCoherenceSync(command.Damagersync));
        }
    
        private void BakeCommandBinding__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6_CommandTarget = (global::Dummy)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Dummy.ParrySync", "(System.Int32Coherence.Toolkit.CoherenceSync)", SendCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6, ReceiveLocalCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6, MessageTarget.All, _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6_CommandTarget, false);
        }
        
        private void SendCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6(MessageTarget target, object[] args)
        {
            var command = new _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6();
            
            int i = 0;
            command.damage = (System.Int32)args[i++];
            command.DamagerSync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6(MessageTarget target, object[] args)
        {
            var command = new _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6();
            
            int i = 0;
            command.damage = (System.Int32)args[i++];
            command.DamagerSync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
            
            ReceiveCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6(command);
        }

        private void ReceiveCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6(_c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6 command)
        {
            var target = _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6_CommandTarget;
            
            target.ParrySync((System.Int32)(command.damage),bridge.EntityIdToCoherenceSync(command.DamagerSync));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5 castedCommand:
                    ReceiveCommand__c473af9c10567024caf206bf6752a656_e33d948cb4b64ce2816cba73ee1638b5(castedCommand);
                    break;
                case _c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f castedCommand:
                    ReceiveCommand__c473af9c10567024caf206bf6752a656_df4c30db719f4e8494aee9fa09f11b9f(castedCommand);
                    break;
                case _c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6 castedCommand:
                    ReceiveCommand__c473af9c10567024caf206bf6752a656_1c65cbe28daf476c87b1ab1f32198cf6(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_c473af9c10567024caf206bf6752a656 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_c473af9c10567024caf206bf6752a656>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}