// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_7b431ba1aca14121881b7291ec1d954a : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_6c6cbe72f4c7443483b0b53111f82bff : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_bc267e2881574efeac1f607b74669b74 : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_97fe5901d0ec4ac9b77cda3d2c193fd2 : BoolBinding
    {   
        private global::Potion CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Potion)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dd4f693a5d019d14ca62105d6772297f_3131434906551989761);
        public override string CoherenceComponentName => "_dd4f693a5d019d14ca62105d6772297f_3131434906551989761";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.m_IsHeld); }
            set { CastedUnityComponent.m_IsHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dd4f693a5d019d14ca62105d6772297f_3131434906551989761)coherenceComponent).m_IsHeld;

            var simFrame = ((_dd4f693a5d019d14ca62105d6772297f_3131434906551989761)coherenceComponent).m_IsHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dd4f693a5d019d14ca62105d6772297f_3131434906551989761)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.m_IsHeld = Value;
            }
            else
            {
                update.m_IsHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.m_IsHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dd4f693a5d019d14ca62105d6772297f_3131434906551989761();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_be02bc06cf11477b89b7abedcb2c5a69 : BoolBinding
    {   
        private global::Potion CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Potion)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dd4f693a5d019d14ca62105d6772297f_3131434906551989761);
        public override string CoherenceComponentName => "_dd4f693a5d019d14ca62105d6772297f_3131434906551989761";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.IsNPCHeld); }
            set { CastedUnityComponent.IsNPCHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dd4f693a5d019d14ca62105d6772297f_3131434906551989761)coherenceComponent).IsNPCHeld;

            var simFrame = ((_dd4f693a5d019d14ca62105d6772297f_3131434906551989761)coherenceComponent).IsNPCHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dd4f693a5d019d14ca62105d6772297f_3131434906551989761)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsNPCHeld = Value;
            }
            else
            {
                update.IsNPCHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsNPCHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dd4f693a5d019d14ca62105d6772297f_3131434906551989761();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_ec7f940015024016a51d4588c5334c99 : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dd4f693a5d019d14ca62105d6772297f_7799190213565977493);
        public override string CoherenceComponentName => "_dd4f693a5d019d14ca62105d6772297f_7799190213565977493";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dd4f693a5d019d14ca62105d6772297f_7799190213565977493)coherenceComponent).path;

            var simFrame = ((_dd4f693a5d019d14ca62105d6772297f_7799190213565977493)coherenceComponent).pathSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dd4f693a5d019d14ca62105d6772297f_7799190213565977493)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.path = Value;
            }
            else
            {
                update.path = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dd4f693a5d019d14ca62105d6772297f_7799190213565977493();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_7b9f19e2510a42dc8dbbf5653f998cff : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dd4f693a5d019d14ca62105d6772297f_7799190213565977493);
        public override string CoherenceComponentName => "_dd4f693a5d019d14ca62105d6772297f_7799190213565977493";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dd4f693a5d019d14ca62105d6772297f_7799190213565977493)coherenceComponent).pathDirtyCounter;

            var simFrame = ((_dd4f693a5d019d14ca62105d6772297f_7799190213565977493)coherenceComponent).pathDirtyCounterSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dd4f693a5d019d14ca62105d6772297f_7799190213565977493)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.pathDirtyCounter = Value;
            }
            else
            {
                update.pathDirtyCounter = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathDirtyCounterSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dd4f693a5d019d14ca62105d6772297f_7799190213565977493();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_1c359ee8f5794bcfbdfe838ce7762900 : BoolBinding
    {   
        private global::UnityEngine.Rigidbody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Rigidbody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dd4f693a5d019d14ca62105d6772297f_6758959841096172205);
        public override string CoherenceComponentName => "_dd4f693a5d019d14ca62105d6772297f_6758959841096172205";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isKinematic); }
            set { CastedUnityComponent.isKinematic = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dd4f693a5d019d14ca62105d6772297f_6758959841096172205)coherenceComponent).isKinematic;

            var simFrame = ((_dd4f693a5d019d14ca62105d6772297f_6758959841096172205)coherenceComponent).isKinematicSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dd4f693a5d019d14ca62105d6772297f_6758959841096172205)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isKinematic = Value;
            }
            else
            {
                update.isKinematic = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isKinematicSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dd4f693a5d019d14ca62105d6772297f_6758959841096172205();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_dd4f693a5d019d14ca62105d6772297f_762bd984b76740c9b04f7c90d207517a : BoolBinding
    {   
        private global::UnityEngine.BoxCollider CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.BoxCollider)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_dd4f693a5d019d14ca62105d6772297f_3875429767672145600);
        public override string CoherenceComponentName => "_dd4f693a5d019d14ca62105d6772297f_3875429767672145600";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_dd4f693a5d019d14ca62105d6772297f_3875429767672145600)coherenceComponent).enabled;

            var simFrame = ((_dd4f693a5d019d14ca62105d6772297f_3875429767672145600)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_dd4f693a5d019d14ca62105d6772297f_3875429767672145600)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _dd4f693a5d019d14ca62105d6772297f_3875429767672145600();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_dd4f693a5d019d14ca62105d6772297f : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_dd4f693a5d019d14ca62105d6772297f>();
        
        private global::Grabbable _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["7b431ba1aca14121881b7291ec1d954a"] = new Binding_dd4f693a5d019d14ca62105d6772297f_7b431ba1aca14121881b7291ec1d954a(),
            ["6c6cbe72f4c7443483b0b53111f82bff"] = new Binding_dd4f693a5d019d14ca62105d6772297f_6c6cbe72f4c7443483b0b53111f82bff(),
            ["bc267e2881574efeac1f607b74669b74"] = new Binding_dd4f693a5d019d14ca62105d6772297f_bc267e2881574efeac1f607b74669b74(),
            ["97fe5901d0ec4ac9b77cda3d2c193fd2"] = new Binding_dd4f693a5d019d14ca62105d6772297f_97fe5901d0ec4ac9b77cda3d2c193fd2(),
            ["be02bc06cf11477b89b7abedcb2c5a69"] = new Binding_dd4f693a5d019d14ca62105d6772297f_be02bc06cf11477b89b7abedcb2c5a69(),
            ["ec7f940015024016a51d4588c5334c99"] = new Binding_dd4f693a5d019d14ca62105d6772297f_ec7f940015024016a51d4588c5334c99(),
            ["7b9f19e2510a42dc8dbbf5653f998cff"] = new Binding_dd4f693a5d019d14ca62105d6772297f_7b9f19e2510a42dc8dbbf5653f998cff(),
            ["1c359ee8f5794bcfbdfe838ce7762900"] = new Binding_dd4f693a5d019d14ca62105d6772297f_1c359ee8f5794bcfbdfe838ce7762900(),
            ["762bd984b76740c9b04f7c90d207517a"] = new Binding_dd4f693a5d019d14ca62105d6772297f_762bd984b76740c9b04f7c90d207517a(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_dd4f693a5d019d14ca62105d6772297f()
        {
            bakedCommandBindings.Add("4891857d5b23463282a1e0edb27559e3", BakeCommandBinding__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3_CommandTarget = (global::Grabbable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Grabbable.EnableComponent", "(System.Boolean)", SendCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3, ReceiveLocalCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3, MessageTarget.All, _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3_CommandTarget, false);
        }
        
        private void SendCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
            
            ReceiveCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3(command);
        }

        private void ReceiveCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3(_dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3 command)
        {
            var target = _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3_CommandTarget;
            
            target.EnableComponent((System.Boolean)(command.enable));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3 castedCommand:
                    ReceiveCommand__dd4f693a5d019d14ca62105d6772297f_4891857d5b23463282a1e0edb27559e3(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_dd4f693a5d019d14ca62105d6772297f Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_dd4f693a5d019d14ca62105d6772297f>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
