// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_ea39855f55724b95b2b7e7695da575bc : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_70d05dd1cd45425897cfb663082a74f7 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_0984533925034b768160dfd879fb55cd : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_26c545a454284901a20c7e09b7f2add4 : BoolBinding
    {   
        private global::Shoulders_Armor CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Shoulders_Armor)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.m_IsHeld); }
            set { CastedUnityComponent.m_IsHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748)coherenceComponent).m_IsHeld;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748)coherenceComponent).m_IsHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.m_IsHeld = Value;
            }
            else
            {
                update.m_IsHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.m_IsHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_752856ac9900488f9134964e028df84a : BoolBinding
    {   
        private global::Shoulders_Armor CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Shoulders_Armor)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.IsNPCHeld); }
            set { CastedUnityComponent.IsNPCHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748)coherenceComponent).IsNPCHeld;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748)coherenceComponent).IsNPCHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsNPCHeld = Value;
            }
            else
            {
                update.IsNPCHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsNPCHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_6247734567211433748();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_a4e3d56e6e1745cf8d72c9e4e42dbc69 : BoolBinding
    {   
        private global::UnityEngine.Rigidbody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Rigidbody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_8848058704849903042);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_8848058704849903042";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isKinematic); }
            set { CastedUnityComponent.isKinematic = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_8848058704849903042)coherenceComponent).isKinematic;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_8848058704849903042)coherenceComponent).isKinematicSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_8848058704849903042)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isKinematic = Value;
            }
            else
            {
                update.isKinematic = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isKinematicSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_8848058704849903042();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_934c4873e882488094ec36fe4fae9286 : BoolBinding
    {   
        private global::UnityEngine.BoxCollider CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.BoxCollider)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_7232497783675306652);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_7232497783675306652";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_7232497783675306652)coherenceComponent).enabled;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_7232497783675306652)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_7232497783675306652)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_7232497783675306652();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_2f2e39f4af15400e8091daa1dd58f2c0 : BoolBinding
    {   
        private global::UnityEngine.MeshRenderer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.MeshRenderer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_1124373291744692987);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_1124373291744692987";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_1124373291744692987)coherenceComponent).enabled;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_1124373291744692987)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_1124373291744692987)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_1124373291744692987();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_82a427abffd341f2866699913eb5e15a : BoolBinding
    {   
        private global::UnityEngine.MeshRenderer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.MeshRenderer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_4174491460896577714);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_4174491460896577714";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_4174491460896577714)coherenceComponent).enabled;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_4174491460896577714)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_4174491460896577714)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_4174491460896577714();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_9e0b016cde744102b4beca6914efe9dd : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077)coherenceComponent).path;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077)coherenceComponent).pathSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.path = Value;
            }
            else
            {
                update.path = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5ca4159d3bce41449a6ca5773f57e7ef_bfe784f8cc494153ad459b94ac460536 : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077);
        public override string CoherenceComponentName => "_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077)coherenceComponent).pathDirtyCounter;

            var simFrame = ((_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077)coherenceComponent).pathDirtyCounterSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.pathDirtyCounter = Value;
            }
            else
            {
                update.pathDirtyCounter = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathDirtyCounterSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5ca4159d3bce41449a6ca5773f57e7ef_1046041548547050077();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_5ca4159d3bce41449a6ca5773f57e7ef : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_5ca4159d3bce41449a6ca5773f57e7ef>();
        
        private global::Grabbable _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["ea39855f55724b95b2b7e7695da575bc"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_ea39855f55724b95b2b7e7695da575bc(),
            ["70d05dd1cd45425897cfb663082a74f7"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_70d05dd1cd45425897cfb663082a74f7(),
            ["0984533925034b768160dfd879fb55cd"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_0984533925034b768160dfd879fb55cd(),
            ["26c545a454284901a20c7e09b7f2add4"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_26c545a454284901a20c7e09b7f2add4(),
            ["752856ac9900488f9134964e028df84a"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_752856ac9900488f9134964e028df84a(),
            ["a4e3d56e6e1745cf8d72c9e4e42dbc69"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_a4e3d56e6e1745cf8d72c9e4e42dbc69(),
            ["934c4873e882488094ec36fe4fae9286"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_934c4873e882488094ec36fe4fae9286(),
            ["2f2e39f4af15400e8091daa1dd58f2c0"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_2f2e39f4af15400e8091daa1dd58f2c0(),
            ["82a427abffd341f2866699913eb5e15a"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_82a427abffd341f2866699913eb5e15a(),
            ["9e0b016cde744102b4beca6914efe9dd"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_9e0b016cde744102b4beca6914efe9dd(),
            ["bfe784f8cc494153ad459b94ac460536"] = new Binding_5ca4159d3bce41449a6ca5773f57e7ef_bfe784f8cc494153ad459b94ac460536(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_5ca4159d3bce41449a6ca5773f57e7ef()
        {
            bakedCommandBindings.Add("82a6c4de14884f93853a6b65801a1488", BakeCommandBinding__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488_CommandTarget = (global::Grabbable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Grabbable.EnableComponent", "(System.Boolean)", SendCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488, ReceiveLocalCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488, MessageTarget.All, _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488_CommandTarget, false);
        }
        
        private void SendCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
            
            ReceiveCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488(command);
        }

        private void ReceiveCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488(_5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488 command)
        {
            var target = _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488_CommandTarget;
            
            target.EnableComponent((System.Boolean)(command.enable));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488 castedCommand:
                    ReceiveCommand__5ca4159d3bce41449a6ca5773f57e7ef_82a6c4de14884f93853a6b65801a1488(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_5ca4159d3bce41449a6ca5773f57e7ef Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_5ca4159d3bce41449a6ca5773f57e7ef>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
