// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_088630e7e256450384c31493d548dc36 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_db478ef9d3a8424a884fb75622bf56dc : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_71b84834f7fe420ea2e2d3b8e086f4af : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_18342032c4ed47c6a47f4a004e8bac35 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5358ed04715b0f148a60e93c83f08be0_1947441686218104907);
        public override string CoherenceComponentName => "_5358ed04715b0f148a60e93c83f08be0_1947441686218104907";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).MoveSpeed;

            var simFrame = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).MoveSpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.MoveSpeed = Value;
            }
            else
            {
                update.MoveSpeed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.MoveSpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5358ed04715b0f148a60e93c83f08be0_1947441686218104907();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_fd2f769f062442ca99319772777717d8 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5358ed04715b0f148a60e93c83f08be0_1947441686218104907);
        public override string CoherenceComponentName => "_5358ed04715b0f148a60e93c83f08be0_1947441686218104907";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).Grounded;

            var simFrame = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).GroundedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Grounded = Value;
            }
            else
            {
                update.Grounded = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.GroundedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5358ed04715b0f148a60e93c83f08be0_1947441686218104907();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_f43fa8897d654f8889da0d0d40f68806 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5358ed04715b0f148a60e93c83f08be0_1947441686218104907);
        public override string CoherenceComponentName => "_5358ed04715b0f148a60e93c83f08be0_1947441686218104907";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).CarryingBig;

            var simFrame = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).CarryingBigSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.CarryingBig = Value;
            }
            else
            {
                update.CarryingBig = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.CarryingBigSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5358ed04715b0f148a60e93c83f08be0_1947441686218104907();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_bd69af8816a54e838a43a60c98980ee4 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5358ed04715b0f148a60e93c83f08be0_1947441686218104907);
        public override string CoherenceComponentName => "_5358ed04715b0f148a60e93c83f08be0_1947441686218104907";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).CarryingSmall;

            var simFrame = ((_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent).CarryingSmallSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5358ed04715b0f148a60e93c83f08be0_1947441686218104907)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.CarryingSmall = Value;
            }
            else
            {
                update.CarryingSmall = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.CarryingSmallSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5358ed04715b0f148a60e93c83f08be0_1947441686218104907();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_2dc7519395064fc2b87f5129f87c7d85 : IntBinding
    {   
        private global::PlayerClothes CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::PlayerClothes)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5358ed04715b0f148a60e93c83f08be0_2130127191657380802);
        public override string CoherenceComponentName => "_5358ed04715b0f148a60e93c83f08be0_2130127191657380802";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.m_BodyTextureIndex); }
            set { CastedUnityComponent.m_BodyTextureIndex = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5358ed04715b0f148a60e93c83f08be0_2130127191657380802)coherenceComponent).m_BodyTextureIndex;

            var simFrame = ((_5358ed04715b0f148a60e93c83f08be0_2130127191657380802)coherenceComponent).m_BodyTextureIndexSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5358ed04715b0f148a60e93c83f08be0_2130127191657380802)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.m_BodyTextureIndex = Value;
            }
            else
            {
                update.m_BodyTextureIndex = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.m_BodyTextureIndexSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5358ed04715b0f148a60e93c83f08be0_2130127191657380802();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_5358ed04715b0f148a60e93c83f08be0_9e1dd35424a747bd8cb23b82e4083c6c : BoolBinding
    {   
        private global::PlayerControls.PlayerUse CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::PlayerControls.PlayerUse)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_5358ed04715b0f148a60e93c83f08be0_58566053745997887);
        public override string CoherenceComponentName => "_5358ed04715b0f148a60e93c83f08be0_58566053745997887";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.m_ItemInUse); }
            set { CastedUnityComponent.m_ItemInUse = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_5358ed04715b0f148a60e93c83f08be0_58566053745997887)coherenceComponent).m_ItemInUse;

            var simFrame = ((_5358ed04715b0f148a60e93c83f08be0_58566053745997887)coherenceComponent).m_ItemInUseSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_5358ed04715b0f148a60e93c83f08be0_58566053745997887)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.m_ItemInUse = Value;
            }
            else
            {
                update.m_ItemInUse = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.m_ItemInUseSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _5358ed04715b0f148a60e93c83f08be0_58566053745997887();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_5358ed04715b0f148a60e93c83f08be0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_5358ed04715b0f148a60e93c83f08be0>();
        
        private global::UnityEngine.Animator _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff_CommandTarget;
        private global::PlayerClothes _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7_CommandTarget;
        private global::TinyPlayer _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["088630e7e256450384c31493d548dc36"] = new Binding_5358ed04715b0f148a60e93c83f08be0_088630e7e256450384c31493d548dc36(),
            ["db478ef9d3a8424a884fb75622bf56dc"] = new Binding_5358ed04715b0f148a60e93c83f08be0_db478ef9d3a8424a884fb75622bf56dc(),
            ["71b84834f7fe420ea2e2d3b8e086f4af"] = new Binding_5358ed04715b0f148a60e93c83f08be0_71b84834f7fe420ea2e2d3b8e086f4af(),
            ["18342032c4ed47c6a47f4a004e8bac35"] = new Binding_5358ed04715b0f148a60e93c83f08be0_18342032c4ed47c6a47f4a004e8bac35(),
            ["fd2f769f062442ca99319772777717d8"] = new Binding_5358ed04715b0f148a60e93c83f08be0_fd2f769f062442ca99319772777717d8(),
            ["f43fa8897d654f8889da0d0d40f68806"] = new Binding_5358ed04715b0f148a60e93c83f08be0_f43fa8897d654f8889da0d0d40f68806(),
            ["bd69af8816a54e838a43a60c98980ee4"] = new Binding_5358ed04715b0f148a60e93c83f08be0_bd69af8816a54e838a43a60c98980ee4(),
            ["2dc7519395064fc2b87f5129f87c7d85"] = new Binding_5358ed04715b0f148a60e93c83f08be0_2dc7519395064fc2b87f5129f87c7d85(),
            ["9e1dd35424a747bd8cb23b82e4083c6c"] = new Binding_5358ed04715b0f148a60e93c83f08be0_9e1dd35424a747bd8cb23b82e4083c6c(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_5358ed04715b0f148a60e93c83f08be0()
        {
            bakedCommandBindings.Add("1acf624c9c73468c81732449828bf8ff", BakeCommandBinding__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff);
            bakedCommandBindings.Add("0ffc5a7e1fd04f489472cf9e12415bf7", BakeCommandBinding__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7);
            bakedCommandBindings.Add("dc362dd6cca24e2995ad9011ec93c5e3", BakeCommandBinding__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff_CommandTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("UnityEngine.Animator.SetTrigger", "(System.String)", SendCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff, ReceiveLocalCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff, MessageTarget.All, _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff_CommandTarget, false);
        }
        
        private void SendCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff(MessageTarget target, object[] args)
        {
            var command = new _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff();
            
            int i = 0;
            command.name = (System.String)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff(MessageTarget target, object[] args)
        {
            var command = new _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff();
            
            int i = 0;
            command.name = (System.String)args[i++];
            
            ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff(command);
        }

        private void ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff(_5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff command)
        {
            var target = _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff_CommandTarget;
            
            target.SetTrigger((System.String)(command.name));
        }
    
        private void BakeCommandBinding__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7_CommandTarget = (global::PlayerClothes)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("PlayerClothes.ChangeBody", "(System.Int32System.Int32)", SendCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7, ReceiveLocalCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7, MessageTarget.All, _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7_CommandTarget, false);
        }
        
        private void SendCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7(MessageTarget target, object[] args)
        {
            var command = new _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7();
            
            int i = 0;
            command.oldIndex = (System.Int32)args[i++];
            command.Newindex = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7(MessageTarget target, object[] args)
        {
            var command = new _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7();
            
            int i = 0;
            command.oldIndex = (System.Int32)args[i++];
            command.Newindex = (System.Int32)args[i++];
            
            ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7(command);
        }

        private void ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7(_5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7 command)
        {
            var target = _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7_CommandTarget;
            
            target.ChangeBody((System.Int32)(command.oldIndex),(System.Int32)(command.Newindex));
        }
    
        private void BakeCommandBinding__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3_CommandTarget = (global::TinyPlayer)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("TinyPlayer.TeleportPlayer", "(UnityEngine.Vector3)", SendCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3, ReceiveLocalCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3, MessageTarget.All, _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3_CommandTarget, false);
        }
        
        private void SendCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3(MessageTarget target, object[] args)
        {
            var command = new _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3();
            
            int i = 0;
            command.worldPos = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3(MessageTarget target, object[] args)
        {
            var command = new _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3();
            
            int i = 0;
            command.worldPos = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3(command);
        }

        private void ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3(_5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3 command)
        {
            var target = _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3_CommandTarget;
            
            target.TeleportPlayer((UnityEngine.Vector3)(command.worldPos));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff castedCommand:
                    ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_1acf624c9c73468c81732449828bf8ff(castedCommand);
                    break;
                case _5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7 castedCommand:
                    ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_0ffc5a7e1fd04f489472cf9e12415bf7(castedCommand);
                    break;
                case _5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3 castedCommand:
                    ReceiveCommand__5358ed04715b0f148a60e93c83f08be0_dc362dd6cca24e2995ad9011ec93c5e3(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_5358ed04715b0f148a60e93c83f08be0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_5358ed04715b0f148a60e93c83f08be0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}