// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_0e075063fb18424282823e79e81dd576 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_58c2a149a2914fb8a73bfb1ef0160c5e : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_77d4e83346c24cc5b4469ee50e1f7aff : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_13a57f40537b46e3ac73d20a7cf7b78c : BoolBinding
    {   
        private global::BasicWeapon CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::BasicWeapon)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f16d1bc84b720e41945040d44446e92_4055558226076958478);
        public override string CoherenceComponentName => "_0f16d1bc84b720e41945040d44446e92_4055558226076958478";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.m_IsHeld); }
            set { CastedUnityComponent.m_IsHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f16d1bc84b720e41945040d44446e92_4055558226076958478)coherenceComponent).m_IsHeld;

            var simFrame = ((_0f16d1bc84b720e41945040d44446e92_4055558226076958478)coherenceComponent).m_IsHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f16d1bc84b720e41945040d44446e92_4055558226076958478)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.m_IsHeld = Value;
            }
            else
            {
                update.m_IsHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.m_IsHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f16d1bc84b720e41945040d44446e92_4055558226076958478();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_9ca34ebc26da405f8370ae5ce989c2ed : BoolBinding
    {   
        private global::BasicWeapon CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::BasicWeapon)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f16d1bc84b720e41945040d44446e92_4055558226076958478);
        public override string CoherenceComponentName => "_0f16d1bc84b720e41945040d44446e92_4055558226076958478";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.IsNPCHeld); }
            set { CastedUnityComponent.IsNPCHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f16d1bc84b720e41945040d44446e92_4055558226076958478)coherenceComponent).IsNPCHeld;

            var simFrame = ((_0f16d1bc84b720e41945040d44446e92_4055558226076958478)coherenceComponent).IsNPCHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f16d1bc84b720e41945040d44446e92_4055558226076958478)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsNPCHeld = Value;
            }
            else
            {
                update.IsNPCHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsNPCHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f16d1bc84b720e41945040d44446e92_4055558226076958478();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_c0c8579c969640d991b0f90e6df02026 : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f16d1bc84b720e41945040d44446e92_8466982124699937639);
        public override string CoherenceComponentName => "_0f16d1bc84b720e41945040d44446e92_8466982124699937639";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f16d1bc84b720e41945040d44446e92_8466982124699937639)coherenceComponent).path;

            var simFrame = ((_0f16d1bc84b720e41945040d44446e92_8466982124699937639)coherenceComponent).pathSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f16d1bc84b720e41945040d44446e92_8466982124699937639)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.path = Value;
            }
            else
            {
                update.path = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f16d1bc84b720e41945040d44446e92_8466982124699937639();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_d8d34e5ca56e47ec8b7976a942b9256d : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f16d1bc84b720e41945040d44446e92_8466982124699937639);
        public override string CoherenceComponentName => "_0f16d1bc84b720e41945040d44446e92_8466982124699937639";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f16d1bc84b720e41945040d44446e92_8466982124699937639)coherenceComponent).pathDirtyCounter;

            var simFrame = ((_0f16d1bc84b720e41945040d44446e92_8466982124699937639)coherenceComponent).pathDirtyCounterSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f16d1bc84b720e41945040d44446e92_8466982124699937639)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.pathDirtyCounter = Value;
            }
            else
            {
                update.pathDirtyCounter = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathDirtyCounterSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f16d1bc84b720e41945040d44446e92_8466982124699937639();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_76cca3f4f88744268881834be5238550 : BoolBinding
    {   
        private global::UnityEngine.Rigidbody CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Rigidbody)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f16d1bc84b720e41945040d44446e92_5885151061618887952);
        public override string CoherenceComponentName => "_0f16d1bc84b720e41945040d44446e92_5885151061618887952";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.isKinematic); }
            set { CastedUnityComponent.isKinematic = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f16d1bc84b720e41945040d44446e92_5885151061618887952)coherenceComponent).isKinematic;

            var simFrame = ((_0f16d1bc84b720e41945040d44446e92_5885151061618887952)coherenceComponent).isKinematicSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f16d1bc84b720e41945040d44446e92_5885151061618887952)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.isKinematic = Value;
            }
            else
            {
                update.isKinematic = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.isKinematicSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f16d1bc84b720e41945040d44446e92_5885151061618887952();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f16d1bc84b720e41945040d44446e92_556dd49c13a7499493ad88b9cd522da6 : BoolBinding
    {   
        private global::UnityEngine.BoxCollider CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.BoxCollider)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f16d1bc84b720e41945040d44446e92_1733633089735608209);
        public override string CoherenceComponentName => "_0f16d1bc84b720e41945040d44446e92_1733633089735608209";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f16d1bc84b720e41945040d44446e92_1733633089735608209)coherenceComponent).enabled;

            var simFrame = ((_0f16d1bc84b720e41945040d44446e92_1733633089735608209)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f16d1bc84b720e41945040d44446e92_1733633089735608209)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f16d1bc84b720e41945040d44446e92_1733633089735608209();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0f16d1bc84b720e41945040d44446e92 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0f16d1bc84b720e41945040d44446e92>();
        
        private global::BasicWeapon _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c_CommandTarget;
        private global::Grabbable _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["0e075063fb18424282823e79e81dd576"] = new Binding_0f16d1bc84b720e41945040d44446e92_0e075063fb18424282823e79e81dd576(),
            ["58c2a149a2914fb8a73bfb1ef0160c5e"] = new Binding_0f16d1bc84b720e41945040d44446e92_58c2a149a2914fb8a73bfb1ef0160c5e(),
            ["77d4e83346c24cc5b4469ee50e1f7aff"] = new Binding_0f16d1bc84b720e41945040d44446e92_77d4e83346c24cc5b4469ee50e1f7aff(),
            ["13a57f40537b46e3ac73d20a7cf7b78c"] = new Binding_0f16d1bc84b720e41945040d44446e92_13a57f40537b46e3ac73d20a7cf7b78c(),
            ["9ca34ebc26da405f8370ae5ce989c2ed"] = new Binding_0f16d1bc84b720e41945040d44446e92_9ca34ebc26da405f8370ae5ce989c2ed(),
            ["c0c8579c969640d991b0f90e6df02026"] = new Binding_0f16d1bc84b720e41945040d44446e92_c0c8579c969640d991b0f90e6df02026(),
            ["d8d34e5ca56e47ec8b7976a942b9256d"] = new Binding_0f16d1bc84b720e41945040d44446e92_d8d34e5ca56e47ec8b7976a942b9256d(),
            ["76cca3f4f88744268881834be5238550"] = new Binding_0f16d1bc84b720e41945040d44446e92_76cca3f4f88744268881834be5238550(),
            ["556dd49c13a7499493ad88b9cd522da6"] = new Binding_0f16d1bc84b720e41945040d44446e92_556dd49c13a7499493ad88b9cd522da6(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0f16d1bc84b720e41945040d44446e92()
        {
            bakedCommandBindings.Add("f6e7317eb2d9445693e6de376bc04b1c", BakeCommandBinding__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c);
            bakedCommandBindings.Add("8bcbb68aaa6341eeaa6e0611169304ed", BakeCommandBinding__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c_CommandTarget = (global::BasicWeapon)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("BasicWeapon.SyncHitSound", "(System.Int32)", SendCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c, ReceiveLocalCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c, MessageTarget.All, _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c_CommandTarget, false);
        }
        
        private void SendCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c();
            
            int i = 0;
            command.index = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c();
            
            int i = 0;
            command.index = (System.Int32)args[i++];
            
            ReceiveCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c(command);
        }

        private void ReceiveCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c(_0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c command)
        {
            var target = _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c_CommandTarget;
            
            target.SyncHitSound((System.Int32)(command.index));
        }
    
        private void BakeCommandBinding__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed_CommandTarget = (global::Grabbable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Grabbable.EnableComponent", "(System.Boolean)", SendCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed, ReceiveLocalCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed, MessageTarget.All, _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed_CommandTarget, false);
        }
        
        private void SendCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
            
            ReceiveCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed(command);
        }

        private void ReceiveCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed(_0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed command)
        {
            var target = _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed_CommandTarget;
            
            target.EnableComponent((System.Boolean)(command.enable));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c castedCommand:
                    ReceiveCommand__0f16d1bc84b720e41945040d44446e92_f6e7317eb2d9445693e6de376bc04b1c(castedCommand);
                    break;
                case _0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed castedCommand:
                    ReceiveCommand__0f16d1bc84b720e41945040d44446e92_8bcbb68aaa6341eeaa6e0611169304ed(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0f16d1bc84b720e41945040d44446e92 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0f16d1bc84b720e41945040d44446e92>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
