// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_06cc1b234a074c168c3fe2ff6e759b30 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_95046b921773486bb228a20e4948d8a9 : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_9eb6806e33d5417089b595b664a284af : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_8141087c109742718ba4e41b8a0a81a9 : FloatAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).MoveSpeed;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).MoveSpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.MoveSpeed = Value;
            }
            else
            {
                update.MoveSpeed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.MoveSpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_1e221c952de54a5a8ffd4f0bff85fefe : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).ShieldParry;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).ShieldParrySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ShieldParry = Value;
            }
            else
            {
                update.ShieldParry = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ShieldParrySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_f7be63de1d2c4577afe3c79c3c69569e : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).Parry;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).ParrySimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Parry = Value;
            }
            else
            {
                update.Parry = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ParrySimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_d7af8f357fcd414d80dc08736a16ad88 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000000001000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).Attacking;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).AttackingSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Attacking = Value;
            }
            else
            {
                update.Attacking = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.AttackingSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_9b0ad98ec28946c79aa98adc4fd756fd : IntAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000000010000;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.GetInteger(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetInteger(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).WeaponDirectionNESO;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).WeaponDirectionNESOSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.WeaponDirectionNESO = Value;
            }
            else
            {
                update.WeaponDirectionNESO = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.WeaponDirectionNESOSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_bb6daaf1447941399eb56ec324c3951d : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000000100000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).Stunned;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).StunnedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Stunned = Value;
            }
            else
            {
                update.Stunned = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.StunnedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_8ff978de62ff47de9dff21e9acd12dd1 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_26648702269276731);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_26648702269276731";
        public override uint FieldMask => 0b00000000000000000000000001000000;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).Grounded;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent).GroundedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_26648702269276731)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Grounded = Value;
            }
            else
            {
                update.Grounded = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.GroundedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_26648702269276731();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_62989a85fb8b481f9614ff4848369743 : IntBinding
    {   
        private global::HumanoidNPC CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::HumanoidNPC)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_6363404363339079209);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_6363404363339079209";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.GameID); }
            set { CastedUnityComponent.GameID = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_6363404363339079209)coherenceComponent).GameID;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_6363404363339079209)coherenceComponent).GameIDSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_6363404363339079209)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.GameID = Value;
            }
            else
            {
                update.GameID = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.GameIDSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_6363404363339079209();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_ad640db0807b4841894b53571146c889 : BoolBinding
    {   
        private global::HumanoidNPC CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::HumanoidNPC)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_6363404363339079209);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_6363404363339079209";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.CanAttack); }
            set { CastedUnityComponent.CanAttack = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_6363404363339079209)coherenceComponent).CanAttack;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_6363404363339079209)coherenceComponent).CanAttackSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_6363404363339079209)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.CanAttack = Value;
            }
            else
            {
                update.CanAttack = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.CanAttackSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_6363404363339079209();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_61db515efe9556c45853cdc384e6813b_00ebcc2e3b9943cc9ed537780d9bc6a6 : ByteArrayBinding
    {   
        private global::Coherence.Toolkit.PrefabSyncGroup CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.PrefabSyncGroup)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_61db515efe9556c45853cdc384e6813b_6236027375457903363);
        public override string CoherenceComponentName => "_61db515efe9556c45853cdc384e6813b_6236027375457903363";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Byte[] Value
        {
            get { return (System.Byte[])(CastedUnityComponent.ids); }
            set { CastedUnityComponent.ids = (System.Byte[])(value); }
        }

        protected override (System.Byte[] value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_61db515efe9556c45853cdc384e6813b_6236027375457903363)coherenceComponent).ids;

            var simFrame = ((_61db515efe9556c45853cdc384e6813b_6236027375457903363)coherenceComponent).idsSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_61db515efe9556c45853cdc384e6813b_6236027375457903363)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ids = Value;
            }
            else
            {
                update.ids = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.idsSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _61db515efe9556c45853cdc384e6813b_6236027375457903363();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_61db515efe9556c45853cdc384e6813b : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_61db515efe9556c45853cdc384e6813b>();
        
        private global::EntityCommands _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78_CommandTarget;
        private global::EntityCommands _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0_CommandTarget;
        private global::EntityCommands _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a_CommandTarget;
        private global::EntityCommands _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7_CommandTarget;
        private global::UnityEngine.Animator _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5_CommandTarget;
        private global::UnityEngine.Animator _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e_CommandTarget;
        private global::UnityEngine.Animator _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943_CommandTarget;
        private global::UnityEngine.Animator _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["06cc1b234a074c168c3fe2ff6e759b30"] = new Binding_61db515efe9556c45853cdc384e6813b_06cc1b234a074c168c3fe2ff6e759b30(),
            ["95046b921773486bb228a20e4948d8a9"] = new Binding_61db515efe9556c45853cdc384e6813b_95046b921773486bb228a20e4948d8a9(),
            ["9eb6806e33d5417089b595b664a284af"] = new Binding_61db515efe9556c45853cdc384e6813b_9eb6806e33d5417089b595b664a284af(),
            ["8141087c109742718ba4e41b8a0a81a9"] = new Binding_61db515efe9556c45853cdc384e6813b_8141087c109742718ba4e41b8a0a81a9(),
            ["1e221c952de54a5a8ffd4f0bff85fefe"] = new Binding_61db515efe9556c45853cdc384e6813b_1e221c952de54a5a8ffd4f0bff85fefe(),
            ["f7be63de1d2c4577afe3c79c3c69569e"] = new Binding_61db515efe9556c45853cdc384e6813b_f7be63de1d2c4577afe3c79c3c69569e(),
            ["d7af8f357fcd414d80dc08736a16ad88"] = new Binding_61db515efe9556c45853cdc384e6813b_d7af8f357fcd414d80dc08736a16ad88(),
            ["9b0ad98ec28946c79aa98adc4fd756fd"] = new Binding_61db515efe9556c45853cdc384e6813b_9b0ad98ec28946c79aa98adc4fd756fd(),
            ["bb6daaf1447941399eb56ec324c3951d"] = new Binding_61db515efe9556c45853cdc384e6813b_bb6daaf1447941399eb56ec324c3951d(),
            ["8ff978de62ff47de9dff21e9acd12dd1"] = new Binding_61db515efe9556c45853cdc384e6813b_8ff978de62ff47de9dff21e9acd12dd1(),
            ["62989a85fb8b481f9614ff4848369743"] = new Binding_61db515efe9556c45853cdc384e6813b_62989a85fb8b481f9614ff4848369743(),
            ["ad640db0807b4841894b53571146c889"] = new Binding_61db515efe9556c45853cdc384e6813b_ad640db0807b4841894b53571146c889(),
            ["00ebcc2e3b9943cc9ed537780d9bc6a6"] = new Binding_61db515efe9556c45853cdc384e6813b_00ebcc2e3b9943cc9ed537780d9bc6a6(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_61db515efe9556c45853cdc384e6813b()
        {
            bakedCommandBindings.Add("a0b23c1a60494d56a8600c6612280d78", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78);
            bakedCommandBindings.Add("27692900c74d47cd9b939374f75dd9b0", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0);
            bakedCommandBindings.Add("b685ba58b0d24ddf969589c404419d6a", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a);
            bakedCommandBindings.Add("1b1a00c45fed46f28f78ccefb78b31f7", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7);
            bakedCommandBindings.Add("23c790be1e954b58a8158dc4d10866d5", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5);
            bakedCommandBindings.Add("a918acae1a75477f894684d0abdf3d4e", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e);
            bakedCommandBindings.Add("8a1700f288ef45e6aac8a2ca83715943", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943);
            bakedCommandBindings.Add("54c6ab62e08a42faaf348095f78abb69", BakeCommandBinding__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78_CommandTarget = (global::EntityCommands)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("EntityCommands.TakeMeleeCommand", "(System.Int32Coherence.Toolkit.CoherenceSyncSystem.Int32UnityEngine.Vector3)", SendCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78();
            
            int i = 0;
            command.DirectionNESO = (System.Int32)args[i++];
            command.sync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
            command.damage = (System.Int32)args[i++];
            command.attackerPos = (UnityEngine.Vector3)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78();
            
            int i = 0;
            command.DirectionNESO = (System.Int32)args[i++];
            command.sync = (Entity)bridge.UnityObjectToEntityId(args[i++] as Coherence.Toolkit.CoherenceSync);
            command.damage = (System.Int32)args[i++];
            command.attackerPos = (UnityEngine.Vector3)args[i++];
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78(_61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78 command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78_CommandTarget;
            
            target.TakeMeleeCommand((System.Int32)(command.DirectionNESO),bridge.EntityIdToCoherenceSync(command.sync),(System.Int32)(command.damage),(UnityEngine.Vector3)(command.attackerPos));
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0_CommandTarget = (global::EntityCommands)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("EntityCommands.SyncBlockedCommand", "()", SendCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0();
            
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0(_61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0 command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0_CommandTarget;
            
            target.SyncBlockedCommand();
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a_CommandTarget = (global::EntityCommands)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("EntityCommands.SyncHitCommand", "()", SendCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a();
            
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a();
            
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a(_61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a_CommandTarget;
            
            target.SyncHitCommand();
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7_CommandTarget = (global::EntityCommands)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("EntityCommands.ChangeGameIDCommand", "(System.Int32)", SendCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7();
            
            int i = 0;
            command.gameID = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7();
            
            int i = 0;
            command.gameID = (System.Int32)args[i++];
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7(_61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7 command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7_CommandTarget;
            
            target.ChangeGameIDCommand((System.Int32)(command.gameID));
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5_CommandTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("UnityEngine.Animator.SetTrigger", "(System.Int32)", SendCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5();
            
            int i = 0;
            command.id = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5();
            
            int i = 0;
            command.id = (System.Int32)args[i++];
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5(_61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5 command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5_CommandTarget;
            
            target.SetTrigger((System.Int32)(command.id));
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e_CommandTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("UnityEngine.Animator.SetTrigger", "(System.String)", SendCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e();
            
            int i = 0;
            command.name = (System.String)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e();
            
            int i = 0;
            command.name = (System.String)args[i++];
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e(_61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e_CommandTarget;
            
            target.SetTrigger((System.String)(command.name));
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943_CommandTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("UnityEngine.Animator.ResetTrigger", "(System.String)", SendCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943();
            
            int i = 0;
            command.name = (System.String)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943();
            
            int i = 0;
            command.name = (System.String)args[i++];
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943(_61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943 command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943_CommandTarget;
            
            target.ResetTrigger((System.String)(command.name));
        }
    
        private void BakeCommandBinding__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69_CommandTarget = (global::UnityEngine.Animator)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("UnityEngine.Animator.ResetTrigger", "(System.Int32)", SendCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69, ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69, MessageTarget.All, _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69_CommandTarget, false);
        }
        
        private void SendCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69();
            
            int i = 0;
            command.id = (System.Int32)args[i++];
        
            client.SendCommand(command, target, entityId);
        }
        
        private void ReceiveLocalCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69(MessageTarget target, object[] args)
        {
            var command = new _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69();
            
            int i = 0;
            command.id = (System.Int32)args[i++];
            
            ReceiveCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69(command);
        }

        private void ReceiveCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69(_61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69 command)
        {
            var target = _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69_CommandTarget;
            
            target.ResetTrigger((System.Int32)(command.id));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78 castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_a0b23c1a60494d56a8600c6612280d78(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0 castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_27692900c74d47cd9b939374f75dd9b0(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_b685ba58b0d24ddf969589c404419d6a(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7 castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_1b1a00c45fed46f28f78ccefb78b31f7(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5 castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_23c790be1e954b58a8158dc4d10866d5(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_a918acae1a75477f894684d0abdf3d4e(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943 castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_8a1700f288ef45e6aac8a2ca83715943(castedCommand);
                    break;
                case _61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69 castedCommand:
                    ReceiveCommand__61db515efe9556c45853cdc384e6813b_54c6ab62e08a42faaf348095f78abb69(castedCommand);
                    break;
                default:
                    logger.Warning($"CoherenceSync_61db515efe9556c45853cdc384e6813b Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning($"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_61db515efe9556c45853cdc384e6813b>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}