// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_f9009a87b40c4e78a33f4e6d64c222b9 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_0114e639ed0449e6a4676e248d5e20ea : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_66560ecc4c154b0fa3c5e1bdf27293a4 : ScaleBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(GenericScale);
        public override string CoherenceComponentName => "GenericScale";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherenceLocalScale); }
            set { coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((GenericScale)coherenceComponent).value;

            var simFrame = ((GenericScale)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (GenericScale)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new GenericScale();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_c28c629830684142963c949207ac1c9e : StringBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796);
        public override string CoherenceComponentName => "_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.path); }
            set { CastedUnityComponent.path = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796)coherenceComponent).path;

            var simFrame = ((_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796)coherenceComponent).pathSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.path = Value;
            }
            else
            {
                update.path = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_e313a294bce14422996d8b1d2099065e : IntBinding
    {   
        private global::Coherence.Toolkit.CoherenceNode CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.Toolkit.CoherenceNode)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796);
        public override string CoherenceComponentName => "_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.pathDirtyCounter); }
            set { CastedUnityComponent.pathDirtyCounter = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796)coherenceComponent).pathDirtyCounter;

            var simFrame = ((_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796)coherenceComponent).pathDirtyCounterSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.pathDirtyCounter = Value;
            }
            else
            {
                update.pathDirtyCounter = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.pathDirtyCounterSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f6b5aa5bcd577f4aa6ed491962442e0_1923514185311723796();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_2a5f7e244c6c4b6489031aeee564634f : BoolBinding
    {   
        private global::UnityEngine.MeshRenderer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.MeshRenderer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f6b5aa5bcd577f4aa6ed491962442e0_2421689411287955229);
        public override string CoherenceComponentName => "_0f6b5aa5bcd577f4aa6ed491962442e0_2421689411287955229";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f6b5aa5bcd577f4aa6ed491962442e0_2421689411287955229)coherenceComponent).enabled;

            var simFrame = ((_0f6b5aa5bcd577f4aa6ed491962442e0_2421689411287955229)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f6b5aa5bcd577f4aa6ed491962442e0_2421689411287955229)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f6b5aa5bcd577f4aa6ed491962442e0_2421689411287955229();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_190f1e7266824d62bfd0b84688eecc9c : BoolBinding
    {   
        private global::Scroll CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Scroll)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116);
        public override string CoherenceComponentName => "_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.m_IsHeld); }
            set { CastedUnityComponent.m_IsHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116)coherenceComponent).m_IsHeld;

            var simFrame = ((_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116)coherenceComponent).m_IsHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.m_IsHeld = Value;
            }
            else
            {
                update.m_IsHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.m_IsHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116();
        }    
    }
    
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f6b5aa5bcd577f4aa6ed491962442e0_9f1effb94ad34ca6bf22d9b3381e32e4 : BoolBinding
    {   
        private global::Scroll CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Scroll)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116);
        public override string CoherenceComponentName => "_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.IsNPCHeld); }
            set { CastedUnityComponent.IsNPCHeld = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116)coherenceComponent).IsNPCHeld;

            var simFrame = ((_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116)coherenceComponent).IsNPCHeldSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.IsNPCHeld = Value;
            }
            else
            {
                update.IsNPCHeld = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.IsNPCHeldSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f6b5aa5bcd577f4aa6ed491962442e0_17161935702122925116();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0f6b5aa5bcd577f4aa6ed491962442e0 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0f6b5aa5bcd577f4aa6ed491962442e0>();
        
        private global::Grabbable _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974_CommandTarget;
        private global::Grabbable _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
            ["f9009a87b40c4e78a33f4e6d64c222b9"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_f9009a87b40c4e78a33f4e6d64c222b9(),
            ["0114e639ed0449e6a4676e248d5e20ea"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_0114e639ed0449e6a4676e248d5e20ea(),
            ["66560ecc4c154b0fa3c5e1bdf27293a4"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_66560ecc4c154b0fa3c5e1bdf27293a4(),
            ["c28c629830684142963c949207ac1c9e"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_c28c629830684142963c949207ac1c9e(),
            ["e313a294bce14422996d8b1d2099065e"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_e313a294bce14422996d8b1d2099065e(),
            ["2a5f7e244c6c4b6489031aeee564634f"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_2a5f7e244c6c4b6489031aeee564634f(),
            ["190f1e7266824d62bfd0b84688eecc9c"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_190f1e7266824d62bfd0b84688eecc9c(),
            ["9f1effb94ad34ca6bf22d9b3381e32e4"] = new Binding_0f6b5aa5bcd577f4aa6ed491962442e0_9f1effb94ad34ca6bf22d9b3381e32e4(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0f6b5aa5bcd577f4aa6ed491962442e0()
        {
            bakedCommandBindings.Add("ab41fa3c66954f7bb28be9b40c525974", BakeCommandBinding__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974);
            bakedCommandBindings.Add("774436e8a67a429c9e36d53657e00995", BakeCommandBinding__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
    
        private void BakeCommandBinding__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974_CommandTarget = (global::Grabbable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Grabbable.EnableComponent", "(System.Boolean)", SendCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974, ReceiveLocalCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974, MessageTarget.All, _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974_CommandTarget, false);
        }
        
        private void SendCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974();
            
            int i = 0;
            command.enable = (System.Boolean)args[i++];
            
            ReceiveCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974(command);
        }

        private void ReceiveCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974(_0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974 command)
        {
            var target = _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974_CommandTarget;
            
            target.EnableComponent((System.Boolean)(command.enable));
        }
    
        private void BakeCommandBinding__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995_CommandTarget = (global::Grabbable)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand("Grabbable.DestroyGrabbable", "()", SendCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995, ReceiveLocalCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995, MessageTarget.All, _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995_CommandTarget, false);
        }
        
        private void SendCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995(MessageTarget target, ChannelID channelID, object[] args)
        {
            var command = new _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995();
            
        
            client.SendCommand(command, target, entityId, channelID);
        }
        
        private void ReceiveLocalCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995(MessageTarget target, ChannelID _, object[] args)
        {
            var command = new _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995();
            
            
            ReceiveCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995(command);
        }

        private void ReceiveCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995(_0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995 command)
        {
            var target = _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995_CommandTarget;
            
            target.DestroyGrabbable();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974 castedCommand:
                    ReceiveCommand__0f6b5aa5bcd577f4aa6ed491962442e0_ab41fa3c66954f7bb28be9b40c525974(castedCommand);
                    break;
                case _0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995 castedCommand:
                    ReceiveCommand__0f6b5aa5bcd577f4aa6ed491962442e0_774436e8a67a429c9e36d53657e00995(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0f6b5aa5bcd577f4aa6ed491962442e0 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override List<ICoherenceComponentData> CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame)
        {
            if (!usesLodsAtRuntime)
            {
                return null;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                var components = new List<ICoherenceComponentData>()
                {
                    new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                };

                return components;
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
            
            return null;
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0f6b5aa5bcd577f4aa6ed491962442e0>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
